# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.cds
canonical: https://interop.esante.gouv.fr/ig/fhir/cds 
name: CDS
title: Cercle De Soins
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 2.0.1 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2020+
# releaseLabel: trial-use
releaseLabel: final-text
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
  ans.fhir.fr.annuaire: 1.1.0
  hl7.fhir.fr.core: 2.1.0
  ans.fr.terminologies: latest

parameters:
    shownav: 'true'
    pin-canonicals: pin-all
    i18n-default-lang: fr # Default language


pages:
    index.md:
        title: Accueil


menu:
    Accueil: index.html
    Ressources de conformité: artifacts.html

